Update pre push hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,29 +1,26 @@
 #!/bin/bash
+# Protect master and development from accidental commits.
 
-# Protect master from accidental commits.
-echo "===\n>> Pre-commit Hook:: Checking branch name..."
+echo "                                    "
+echo "🏁 Pre-commit Hook: Checking branch name..."
+echo "------------------------------------"
+
 branchName=$(git branch | grep '*' | sed 's/* //')
 
 if [ $branchName == 'master' ]
 then
-  echo "\n🚫 Commit directly to master branch is not allowed! \n" && exit 1
+  echo "🚫 Commit directly to master branch is not allowed!"
+  echo "------------------------------------"
+  echo "                                    "  && exit 1
 fi
 
 if [ $branchName == 'development' ]
 then
-  echo "\n🚫 Cannot push to remote develop branch, please create your own branch and use PR." && exit 1
+  echo "🚫 Cannot push to remote develop branch, please create your own branch and use PR." 
+  echo "------------------------------------" 
+  echo "                                    "  && exit 1
 fi
 
-# if [[ $branchName = *[![:ascii:]]* ]]
-# then
-#   echo "\n🚫 Branch name should not have any ascii and upper case letters, please rename your branch name \n" && exit 1
-# fi
-
-# if [[ $branchName =~ [A-Z] ]]
-# then
-#   echo "\n🚫 Branch name should not have any ascii and upper case letters, please rename your branch name \n" && exit 1
-# fi
-
-echo ">> Finish checking branch name \n==="
+echo "✅ Finish checking branch name."
 
 exit 0
